### ISSUE TITLE
Recursive FROM statements when there is no recursion

### ISSUE THREAD

**Issue by jasonxia** [realestate-com-au/harpoon#6]
It would appear that in this situation you get a recursive FROM statements error

```
images:
  one:
    commands:
      - FROM ubuntu14.04

  two:
    link:
      - "{images.three.container_name}:thing"

    commands:
      - [FROM, "{images.one.image_name}"]

  three:
    commands:
      - [FROM, "{images.two.image_name}"]
```

Even though the images are made separately to the container
